version: 2

jobs:
  "setup_npm_deps":
    docker: &DOCKERIMAGE
      - image: jenkinsrise/cci-v2-launcher-electron:0.0.5
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: node-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  "test_unit":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run:
          command: npm run test
          no_output_timeout: 1m

workflows:
  version: 2
  workflow1:
    jobs:
      - "test_unit":
          requires:
            - setup_npm_deps