version: 2

jobs:
  "test_unit":
    docker: &DOCKERIMAGE
      - image: jenkinsrise/cci-v2-launcher-electron:0.0.5
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: node-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm run test
          no_output_timeout: 1m

  "version":
      docker: *DOCKERIMAGE
      steps:
        - checkout
        - run: echo $(date +%Y.%m.%d.%H.%M) >version
        - persist_to_workspace:
            root: .
            paths:
              - version

  "build":
      docker: *DOCKERIMAGE
      steps:
        - checkout
        - attach_workspace:
            at: .
        - restore_cache:
            key: node-cache-{{ checksum "package.json" }}
        - run: npm run build
        - save_cache:
            key: node-cache-{{ checksum "package.json" }}
            paths:
              - ./node_modules
        - persist_to_workspace:
            root: .
            paths:
              - build

  "stage":
      docker: *DOCKERIMAGE
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run: ./stage.sh

workflows:
  version: 2
  workflow1:
    jobs:
      - "test_unit"
      - "version"
      - "build":
          requires:
            - version
          filters:
            branches:
              only:
                - master
                - /^stage\/.*/
                - /^staging\/.*/
      - "stage":
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - /^stage\/.*/
                - /^staging\/.*/